spring.application.name=medrassa

# ===============================
# =   CONFIGURATION DE L’APPLICATION
# ===============================

# ===============================
# =   CONFIGURATION DE LA BASE DE DONNÉES
# ===============================

# Type de base (ici MySQL)
spring.datasource.url=jdbc:mysql://localhost:3306/ecole_coran_benihaoua?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=admin

# Pilote JDBC pour MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# =   PARAMÈTRES JPA / HIBERNATE
# ===============================

# Dialecte SQL utilisé par Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


# Création automatique du schéma :
# none | validate | update | create | create-drop
spring.jpa.hibernate.ddl-auto=update

# Afficher les requêtes SQL dans la console
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# =   PARAMÈTRES DU SERVEUR EMBARQUÉ
# ===============================

server.port=8080

